apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: cart.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: GET /cart/{id}
      condition:
        method: GET
        pathRegex: "/cart/.*"
    - name: DELETE /cart/{id}
      condition:
        method: DELETE
        pathRegex: "/cart/.*"
    - name: GET /rename/{from}/{to}
      condition:
        method: GET
        pathRegex: "/rename/.*"
    - name: GET /add/{id}/{sku}/{qty}
      condition:
        method: GET
        pathRegex: "/add/.*"
    - name: GET /update/{id}/{sku}/{qty}
      condition:
        method: GET
        pathRegex: "/update/.*"
    - name: POST /shipping/{id}
      condition:
        method: POST
        pathRegex: "/shipping/.*"