apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: catalogue.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: GET /categories
      condition:
        method: GET
        pathRegex: "/categories"
    - name: GET /products
      condition:
        method: GET
        pathRegex: "/products"
    - name: GET /product/{sku}
      condition:
        method: GET
        pathRegex: "/product/.*"