apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: payment.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: POST /pay/{user}
      condition:
        method: POST
        pathRegex: "/pay/[^/]+$"
