apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: ratings.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: PUT /api/rate/{sku}/{score}
      condition:
        method: PUT
        pathRegex: "/api/rate/.*/[0-9]+"
    - name: GET /api/fetch/{sku}
      condition:
        method: GET
        pathRegex: "/api/fetch/.*"