apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: shipping.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: GET /codes
      condition:
        method: GET
        pathRegex: "/codes"
    - name: GET /cities/{code}
      condition:
        method: GET
        pathRegex: "/cities/.*"
    - name: GET /calc/{cityUuid}
      condition:
        method: GET
        pathRegex: "/calc/.*"
    - name: POST /confirm/{user}
      condition:
        method: POST
        pathRegex: "/confirm/.*"