apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: user.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: POST /login
      condition:
        method: POST
        pathRegex: "/login"
    - name: GET /uniqueid
      condition:
        method: GET
        pathRegex: "/uniqueid"