apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: web.application.svc.cluster.local
  namespace: application
spec:
  routes:
    - name: GET /
      condition:
        method: GET
        pathRegex: "/$"

    - name: POST /api/user/login
      condition:
        method: POST
        pathRegex: "/api/user/login"

    - name: GET /api/user/uniqueid
      condition:
        method: GET
        pathRegex: "/api/user/uniqueid"

    - name: GET /api/catalogue/categories
      condition:
        method: GET
        pathRegex: "/api/catalogue/categories"

    - name: GET /api/catalogue/products
      condition:
        method: GET
        pathRegex: "/api/catalogue/products"

    - name: GET /api/catalogue/product/{sku}
      condition:
        method: GET
        pathRegex: "/api/catalogue/product/.*"

    - name: PUT /api/ratings/api/rate/{sku}/{score}
      condition:
        method: PUT
        pathRegex: "/api/ratings/api/rate/.*/[0-9]+"

    - name: GET /api/ratings/api/fetch/{sku}
      condition:
        method: GET
        pathRegex: "/api/ratings/api/fetch/.*"

    - name: GET /api/cart/add/{user}/{sku}/{qty}
      condition:
        method: GET
        pathRegex: "/api/cart/add/.*/.*/[0-9]+"

    - name: GET /api/cart/cart/{user}
      condition:
        method: GET
        pathRegex: "/api/cart/cart/.*"

    - name: GET /api/cart/update/{user}/{sku}/{qty}
      condition:
        method: GET
        pathRegex: "/api/cart/update/.*/.*/[0-9]+"
   

    - name: GET /api/shipping/codes
      condition:
        method: GET
        pathRegex: "/api/shipping/codes"

    - name: GET /api/shipping/cities/{code}
      condition:
        method: GET
        pathRegex: "/api/shipping/cities/.*"

    - name: GET /api/shipping/calc/{cityUuid}
      condition:
        method: GET
        pathRegex: "/api/shipping/calc/.*"

    - name: POST /api/shipping/confirm/{user}
      condition:
        method: POST
        pathRegex: "/api/shipping/confirm/.*"

    - name: POST /api/payment/pay/{user}
      condition:
        method: POST
        pathRegex: "/api/payment/pay/[^/]+$"
