apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: application
  labels:
    service: mongodb
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: ${REPO}/robot-shop-mongo:${TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
    app: mongodb
  name: mongodb
  namespace: application
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
    app: mongodb

