apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: application
  labels:
    service: mysql
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ${REPO}/robot-shop-mysql:${TAG}
        imagePullPolicy: Always
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
--- 

apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
    app: mysql
  name: mysql
  namespace: application
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
    app: mysql

