apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: application
  labels:
    service: rabbitmq
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        service: rabbitmq
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always

--- 

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: application
  labels:
    service: rabbitmq
    app: rabbitmq
spec:
  ports:
  - name: tcp-amqp
    port: 5672
    targetPort: 5672
  - name: http-management
    port: 15672
    targetPort: 15672
  - name: tcp-epmd
    port: 4369
    targetPort: 4369
  selector:
    service: rabbitmq
    app: rabbitmq

