apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: application
  labels:
    service: shipping
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        service: shipping
        app: shipping
    spec:
      containers:
      - name: shipping
        image: ${REPO}/robot-shop-shipping:${TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # it's Java it needs lots of memory
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 15
          successThreshold: 1
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: application
  labels:
    service: shipping
    app: shipping
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: shipping
    app: shipping
